# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repmuni', '0002_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Report_Photos')),
                ('imagedescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('fenomena', models.CharField(choices=[('S', 'Sismo'), ('R', 'Remoción en Masa'), ('I', 'Inundación'), ('A', 'Avenida Torrencial'), ('I', 'Incendio'), ('O', 'Otro')], max_length=1)),
                ('descrip', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAlbums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumTitle', models.CharField(max_length=100)),
                ('AlbumDescription', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repmuni.Photos')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repmuni.Report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='photos',
            field=models.ManyToManyField(through='Repmuni.ReportAlbums', to='Repmuni.Photos'),
        ),
    ]
