# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repmuni', '0003_auto_20180223_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='Report_Photos'),
        ),
    ]
