# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repmuni', '0004_auto_20180305_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportalbums',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='reportalbums',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='photos',
        ),
        migrations.AddField(
            model_name='photos',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Repmuni.Report'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportAlbums',
        ),
    ]
