# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repmuni', '0005_auto_20180404_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='autor',
            new_name='user',
        ),
    ]
